FROM alpine:3.10.2

RUN apk add --update --no-cache \
  build-base \
  nodejs-current \
  curl \
  npm \
  tzdata \
  libxslt \
  openssl \
  git \
  bash

WORKDIR /app

COPY ./shared-libs ./shared-libs
COPY ./api ./api

RUN cd api && npm install --global

EXPOSE 5988

ENTRYPOINT ["/bin/bash", "/app/api/docker-entrypoint.sh"]